name: Copy App Folder to Show Branch

on:
    push:
        branches:
            - master

jobs:
    copy_app_folder:
        runs-on: ubuntu-latest

        steps:
            - name: Check out code
              uses: actions/checkout@v2

            - name: Check if 'show' branch exists
              run: |
                  if git show-ref --quiet refs/heads/show; then
                    git checkout show
                  else
                    git checkout -b show
                  fi

            - name: Copy App Folder

              run: |
                  git config --global user.email "mytest@example.com"
                  git config --global user.name "Dms"

                  # Copy the contents of the 'app' folder from the 'master' branch
                  git checkout master -- app/

                  # Commit the changes
                  git commit -m "Copy 'app' folder from 'master' to 'show' branch"

                  # Push the changes to the 'show' branch
                  git push origin show

            - name: Complete Workflow
              run: echo "App folder copied to 'show' branch."
